FROM mcr.microsoft.com/devcontainers/go:1-1.21-bullseye

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

RUN echo 'we are running some # of cool things'

# [Optional] Uncomment the next lines to use go get to install anything else you need
#USER vscode
#RUN go get -x go get github.com/labstack/echo/v4
#RUN go get -x go get github.com/gocraft/dbr
#USER root

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
